### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by rooskienz** [OmniVirt/OmniVirtAdNetwork-Unity-Example#3]
I get this error in log when running

`if (vrAd.IsCompleted ()) {
        vrAd.LoadAd ();
   }`

Error:
`I chromium: [INFO:CONSOLE(1)] "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://node.vroptimal-3dx-assets.com') does not match the recipient window's origin ('https://static.vroptimal-3dx-assets.com').", source: https://www.vroptimal-3dx-assets.com/scripts/vroptimal.js (1)`

Looks like Cross domain issue.

My setup is: Unity 5.5.3 and running the app on Android 7.0.

**Comment by baddth** [comment]
Hi rooskienz,

This issue should be permanently fixed in our latest SDK. Do you mind pulling our latest master? The SDK is very high performant and robust. Please let us know if that doesn't work with you.

Best,
Brad
